CREATE DATABASE [FinanceAnalyzerDb]
GO
USE [FinanceAnalyzerDb];

CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Login] NVARCHAR(50) NOT NULL,
	PRIMARY KEY CLUSTERED([Id]ASC)
);
GO

CREATE TABLE [dbo].[Income]
(
	[Id] INT IDENTITY (1,1) NOT NULL,
	[UserId] INT NOT NULL,
   	[Amount] DECIMAL NOT NULL,
	FOREIGN KEY ([UserId]) REFERENCES [dbo].[User].[Id],

 	PRIMARY KEY CLUSTERED([Id] ASC)
);
GO

CREATE TABLE [dbo].[Expense]
(
	[Id] INT IDENTITY (1,1) NOT NULL,
	[UserId] INT NOT NULL,
   	[Amount] DECIMAL NOT NULL,
	FOREIGN KEY ([UserId]) REFERENCES [dbo].[User].[Id],

 	PRIMARY KEY CLUSTERED([Id] ASC)
);
GO

CREATE TABLE [dbo].[Tax]
(
	[Id] INT IDENTITY (1,1) NOT NULL,
	[UserId] INT NOT NULL,
   	[Amount] DECIMAL NOT NULL,
	FOREIGN KEY ([UserId]) REFERENCES [dbo].[User].[Id],

 	PRIMARY KEY CLUSTERED([Id] ASC)
);
